media:
  input: assets/img
  output: /assets/img

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: _posts
    filename: "{year}-{month}-{day}-{slug}.md"
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: date
        label: Date
        type: datetime
        required: true

      - name: layout
        label: Layout
        type: string
        default: post

      - name: categories
        label: Categories
        type: list
        items:
          type: string

      - name: body
        label: Content
        type: rich-text
        
  - name: pages
    label: Pages
    type: collection
    path: _pages
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: layout
        label: Layout
        type: string
        default: page

      - name: permalink
        label: Permalink
        type: string

      - name: cover
        label: Cover Image
        type: image

      - name: intro
        label: Page intro
        type: rich-text

      - name: body
        label: Content
        type: rich-text

      - name: sections
        label: Page Sections
        type: block
        list: true # Often used with type: block to allow multiple sections
        blockKey: type # Optional: customize the key used to store the block name, defaults to `_block`
        blocks:
          # Each item defines a possible block structure the user can select.
          # These typically use 'component' or define 'fields' directly.
          - name: hero
            label: Add Hero Section
            component: hero # Assumes a 'hero' component is defined and that its type is `object`
          - name: text
            label: Add Text Block
            fields:
              - name: content
                label: Text Content
                type: rich-text