media:
  input: https://lucian-alexe.github.io/jekyll-with-pages/assets/uploads
  output: /assets/uploads

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: _posts
    filename: "{year}-{month}-{day}-{slug}.md"
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: date
        label: Date
        type: datetime
        required: true

      - name: layout
        label: Layout
        type: string
        default: post

      - name: categories
        label: Categories
        type: list
        items:
          type: string

      - name: body
        label: Content
        type: rich-text

