media:
  input: assets/img
  output: /assets/img

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: _posts
    filename: "{year}-{month}-{day}-{slug}.md"
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: date
        label: Date
        type: datetime
        required: true

      - name: layout
        label: Layout
        type: string
        default: post

      - name: categories
        label: Categories
        type: list
        items:
          type: string

      - name: body
        label: Content
        type: rich-text
        
  - name: pages
    label: Pages
    type: collection
    path: _pages
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: layout
        label: Layout
        type: string
        default: page

      - name: permalink
        label: Permalink
        type: string

      - name: cover
        label: Cover Image
        type: image

      - name: intro
        label: Page intro
        type: rich-text

      - name: body
        label: Content
        type: rich-text

      - name: service_list
        label: Service List (Therapy)
        type: object
        fields:
          - name: heading
            label: Heading
            type: string
          - name: intro_text
            label: Introduction Text
            type: string
          - name: list_items
            label: List Items
            type: list
            field: # This tells PagesCMS each item in the list is a simple text input
              type: string
              label: Item